version: 2.1

orbs:
  accuknox-scan: accuknox/scan@1.0.1

workflows:
  accuknox:
    jobs:
      - accuknox-scan/dast:
          context: Vicky
          TARGET_URL: "http://testphp.vulnweb.com"
          DAST_SCAN_TYPE: "full-scan"
          SEVERITY_THRESHOLD: "medium"
          SOFT_FAIL: true
