version: 2.1

orbs:
  accuknox-scan: accuknox/scan@1.0.1

workflows:
  accuknox:
    jobs:
      - accuknox-scan/iac:
          context: Demo
          FRAMEWORK: "terraform"
          DIRECTORY: "."
          SOFT_FAIL: true


