version: 2.1

orbs:
  accuknox-scan: accuknox/scan@1.0.1

workflows:
  accuknox-sast:
    jobs:
      - accuknox-scan/sast:
          context: Vicky
          SEVERITY_THRESHOLD: "Medium"
          SOFT_FAIL: false
          


