version: 2.1

orbs:
  accuknox-scan: accuknox/scan@1.0.1

workflows:
  accuknox:
    jobs:
      - accuknox-scan/sast:
          context: Demo
          SOFT_FAIL: true
          steps:
            - run:
                name: Print all environment variables
                command: printenv
          
