version: 2.1

orbs:
  accuknox-scan: accuknox/scan@dev:0.3.3

jobs:
  printenv:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: printenv
          command: |
            printenv

workflows:  
  accuknox:
    jobs:
    - printenv
    - accuknox-scan/sast:
        SOFT_FAIL: true
    - accuknox-scan/sq-sast:
        SOFT_FAIL: true
        SKIP_SONAR_SCAN: false
    - accuknox-scan/iac:
        SOFT_FAIL: true
